name: cody
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble_bottom_bar: ^1.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - lib/images/virus.png
  - lib/images/thermometer.png
  - lib/images/spread1.png
  - lib/images/mask.png
  - lib/images/doctor.png
  - lib/images/doctor1.png
  - lib/images/reading.png
  - lib/images/talking.png
  - lib/images/sick.png
  - lib/images/pregnant.png
  - lib/images/condition.png
  - lib/images/old.png
  - lib/images/exclamation.png
  - lib/images/doctor.png
  - lib/images/vaccine.png
  - lib/images/virtual.png
  - lib/images/screening.png
  - lib/images/wash-hands.png
  - lib/images/distancing.png
  - lib/images/stay-home.png
  - lib/images/quarantine.png
  - lib/images/cover.png
  - lib/images/disinfect.png
  - lib/images/monitor-health.png
  - lib/images/call-hospital.png
  - lib/images/no-sharing.png
  - lib/images/prevent-covid.png
  - lib/images/questionnaire.png
  - lib/images/checked.png
  - lib/images/check-mark.png
  - lib/images/screening-doctor.png
  - lib/images/emergency_cross.png
  - lib/images/self-isolation.png
  - lib/images/healthcare-provider.png
  - lib/images/social-distancing.png
  - lib/images/self-isolate.png
  - lib/images/covid-testing.png
  - lib/images/local-centers.png
  - lib/images/question-mark.png
  - lib/images/test-result.png
  - lib/images/waiting-time.png
  - lib/images/symptoms/ache.png
  - lib/images/symptoms/breath.png
  - lib/images/symptoms/chill.png
  - lib/images/symptoms/cough.png
  - lib/images/symptoms/diarrhea.png
  - lib/images/symptoms/fever.png
  - lib/images/symptoms/smell.png
  - lib/images/symptoms/vomit.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf

    - family: Roboto-Regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
